version: "3.8"
services:
  todo-api:
    container_name: todo-api
    build:
      context: ./todo-api # Use the local directory as the build context
      dockerfile: Dockerfile # Use the Dockerfile in the local directory
    ports:
      - "5000:5000" # Map the container port to the host port
    environment:
      MONGO_URI: "mongodb://mongo:27017/todosDB" # Use the service name as the hostname
    volumes:
      - ./todo-api:/app # Mount the local directory to the container
    depends_on:
      - mongo # Wait for the mongo service to be ready
    networks:
      - backend # Connect to the backend network
      - frontend # Connect to the frontend network

  todo-app:
    container_name: todo-app
    build:
      context: ./todo-app # Use the local directory as the build context
      dockerfile: Dockerfile # Use the Dockerfile in the local directory
    ports:
      - "3000:3000" # Map the container port to the host port
    environment:
      VITE_API_URL: "http://localhost:5000"
      CHOKIDAR_USEPOLLING: true # Enable polling for file changes
    volumes:
      - ./todo-app:/app # Mount the local directory to the container
      - /app/node_modules # Prevent the node_modules directory from being mounted
    depends_on:
      - todo-api # Wait for the todo-api service to be ready
    networks:
      - frontend # Connect to the frontend network

  mongo:
    container_name: mongo
    image: mongo:latest # Use the latest MongoDB image
    volumes:
      - mongo-data:/data/db # Persist the data locally
    networks:
      - backend # Connect to the backend network
    ports:
      - "27017:27017" # Map the container port to the host port

networks:
  frontend:
    driver: bridge # Use the default bridge network
  backend:
    driver: bridge # Use the default bridge network

volumes:
  mongo-data:
    driver: local # Use the local volume driver
