version: "3.8"
services:
  todo-api:
    container_name: todo-api
    build:
      context: ./todo-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb://mongo:27017/todosDB"
    volumes:
      - ./todo-api:/app # Mount the local directory to the container
    depends_on:
      - mongo
    networks:
      - backend
      - frontend

  todo-app:
    container_name: todo-app
    build:
      context: ./todo-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: "http://localhost:5000"
      CHOKIDAR_USEPOLLING: true
    volumes:
      - ./todo-app:/app # Mount the local directory to the container
      - /app/node_modules # Prevent the node_modules directory from being mounted
    depends_on:
      - todo-api
    networks:
      - frontend

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongo-data:/data/db # Persist the data locally
    networks:
      - backend
    ports:
      - "27017:27017"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongo-data:
    driver: local
