apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert -o kubernetes/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: todo-app
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert -o kubernetes/
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/todo-fullstack-2025-test-frontend: "true"
        io.kompose.service: todo-app
    spec:
      containers:
        - env:
            - name: CHOKIDAR_USEPOLLING
              value: "true"
            - name: VITE_API_URL
              value: http://localhost:5000
          image: todo-app
          name: todo-app
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: todo-app-claim0
            - mountPath: /app/node_modules
              name: todo-app-claim1
      restartPolicy: Always
      volumes:
        - name: todo-app-claim0
          persistentVolumeClaim:
            claimName: todo-app-claim0
        - name: todo-app-claim1
          persistentVolumeClaim:
            claimName: todo-app-claim1
status: {}
